@startuml packages
set namespaceSeparator none
package "skneuromsi" as skneuromsi {
}
package "skneuromsi.bayesian" as skneuromsi.bayesian {
}
package "skneuromsi.bayesian._kording2007" as skneuromsi.bayesian._kording2007 {
}
package "skneuromsi.bayesian._zhu2024" as skneuromsi.bayesian._zhu2024 {
}
package "skneuromsi.core" as skneuromsi.core {
}
package "skneuromsi.core.constants" as skneuromsi.core.constants {
}
package "skneuromsi.core.modelabc" as skneuromsi.core.modelabc {
}
package "skneuromsi.core.ndresult" as skneuromsi.core.ndresult {
}
package "skneuromsi.core.ndresult.compress" as skneuromsi.core.ndresult.compress {
}
package "skneuromsi.core.ndresult.plot_acc" as skneuromsi.core.ndresult.plot_acc {
}
package "skneuromsi.core.ndresult.result" as skneuromsi.core.ndresult.result {
}
package "skneuromsi.core.ndresult.stats_acc" as skneuromsi.core.ndresult.stats_acc {
}
package "skneuromsi.data" as skneuromsi.data {
}
package "skneuromsi.data.echeveste_data_loader" as skneuromsi.data.echeveste_data_loader {
}
package "skneuromsi.data.gsm_data_loader" as skneuromsi.data.gsm_data_loader {
}
package "skneuromsi.generative" as skneuromsi.generative {
}
package "skneuromsi.generative._gsm" as skneuromsi.generative._gsm {
}
package "skneuromsi.io" as skneuromsi.io {
}
package "skneuromsi.mle" as skneuromsi.mle {
}
package "skneuromsi.mle._alais_burr2004" as skneuromsi.mle._alais_burr2004 {
}
package "skneuromsi.ndcollection" as skneuromsi.ndcollection {
}
package "skneuromsi.ndcollection.bias_acc" as skneuromsi.ndcollection.bias_acc {
}
package "skneuromsi.ndcollection.causes_acc" as skneuromsi.ndcollection.causes_acc {
}
package "skneuromsi.ndcollection.collection" as skneuromsi.ndcollection.collection {
}
package "skneuromsi.ndcollection.cplot_acc" as skneuromsi.ndcollection.cplot_acc {
}
package "skneuromsi.neural" as skneuromsi.neural {
}
package "skneuromsi.neural._cuppini2014" as skneuromsi.neural._cuppini2014 {
}
package "skneuromsi.neural._cuppini2017" as skneuromsi.neural._cuppini2017 {
}
package "skneuromsi.neural._device_config" as skneuromsi.neural._device_config {
}
package "skneuromsi.neural._echeveste2020" as skneuromsi.neural._echeveste2020 {
}
package "skneuromsi.neural._echeveste_training" as skneuromsi.neural._echeveste_training {
}
package "skneuromsi.neural._echeveste_visualization" as skneuromsi.neural._echeveste_visualization {
}
package "skneuromsi.neural._paredes2025" as skneuromsi.neural._paredes2025 {
}
package "skneuromsi.sweep" as skneuromsi.sweep {
}
package "skneuromsi.testing" as skneuromsi.testing {
}
package "skneuromsi.utils" as skneuromsi.utils {
}
package "skneuromsi.utils.accabc" as skneuromsi.utils.accabc {
}
package "skneuromsi.utils.bunch" as skneuromsi.utils.bunch {
}
package "skneuromsi.utils.custom_json" as skneuromsi.utils.custom_json {
}
package "skneuromsi.utils.ddtype_tools" as skneuromsi.utils.ddtype_tools {
}
package "skneuromsi.utils.dict_cmp" as skneuromsi.utils.dict_cmp {
}
package "skneuromsi.utils.doctools" as skneuromsi.utils.doctools {
}
package "skneuromsi.utils.memtools" as skneuromsi.utils.memtools {
}
package "skneuromsi.utils.neural_tools" as skneuromsi.utils.neural_tools {
}
package "skneuromsi.utils.readout_tools" as skneuromsi.utils.readout_tools {
}
skneuromsi --> skneuromsi.core
skneuromsi --> skneuromsi.io
skneuromsi --> skneuromsi.ndcollection
skneuromsi.bayesian --> skneuromsi.bayesian._kording2007
skneuromsi.bayesian --> skneuromsi.bayesian._zhu2024
skneuromsi.core --> skneuromsi.core.constants
skneuromsi.core --> skneuromsi.core.modelabc
skneuromsi.core --> skneuromsi.core.ndresult
skneuromsi.core.modelabc --> skneuromsi.core.ndresult
skneuromsi.core.ndresult --> skneuromsi.core.ndresult.compress
skneuromsi.core.ndresult --> skneuromsi.core.ndresult.result
skneuromsi.core.ndresult.compress --> skneuromsi.core.ndresult.result
skneuromsi.core.ndresult.result --> skneuromsi.core.ndresult.plot_acc
skneuromsi.core.ndresult.result --> skneuromsi.core.ndresult.stats_acc
skneuromsi.data --> skneuromsi.data.echeveste_data_loader
skneuromsi.data --> skneuromsi.data.gsm_data_loader
skneuromsi.generative --> skneuromsi.generative._gsm
skneuromsi.io --> skneuromsi.utils
skneuromsi.io --> skneuromsi.utils.custom_json
skneuromsi.mle --> skneuromsi.mle._alais_burr2004
skneuromsi.ndcollection --> skneuromsi.ndcollection.collection
skneuromsi.neural --> skneuromsi.neural._cuppini2014
skneuromsi.neural --> skneuromsi.neural._cuppini2017
skneuromsi.neural --> skneuromsi.neural._device_config
skneuromsi.neural --> skneuromsi.neural._echeveste2020
skneuromsi.neural --> skneuromsi.neural._paredes2025
skneuromsi.neural._echeveste2020 --> skneuromsi.neural._device_config
skneuromsi.neural._echeveste2020 --> skneuromsi.neural._echeveste_training
skneuromsi.sweep --> skneuromsi.utils
skneuromsi.sweep --> skneuromsi.utils.doctools
skneuromsi.sweep --> skneuromsi.utils.memtools
skneuromsi.testing --> skneuromsi.utils
skneuromsi.testing --> skneuromsi.utils.dict_cmp
skneuromsi.utils --> skneuromsi.utils.accabc
skneuromsi.utils --> skneuromsi.utils.bunch
skneuromsi.utils --> skneuromsi.utils.doctools
@enduml
