#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Independent GSM data loader for Echeveste2020.

This module provides access only to the Gaussian Scale Mixture (GSM)
components used in Echeveste et al. (2020), decoupled from SSN data.
"""

from pathlib import Path

import numpy as np


class GSMDataLoader:
    """Loader for GSM-related data."""

    def __init__(self):
        """Initialize GSM data loader."""
        self.data_path = Path(__file__).parent / "gsm"

        if not self.data_path.exists():
            raise FileNotFoundError(
                f"GSM data directory not found at {self.data_path}"
            )

    # GSM Data Loading Methods
    def load_gabor_filters(self):
        """
        Load pre-trained Gabor filters.

        Returns
        -------
        A : np.ndarray, shape (256, 50)
            Pre-trained Gabor filter matrix from natural image statistics
        """
        return np.loadtxt(self.data_path / "A")

    def load_prior_covariance(self):
        """
        Load prior covariance matrix.

        Returns
        -------
        C : np.ndarray, shape (50, 50)
            Prior covariance matrix learned from natural image statistics
        """
        return np.loadtxt(self.data_path / "C")

    def load_contrast_levels(self):
        """Load available contrast levels.

        Returns
        -------
        contrasts : np.ndarray, shape (10,)
            Array of 10 contrast levels used in the original experiments
        """
        return np.loadtxt(self.data_path / "z_array")

    # Stimuli
    def load_stimulus(self, contrast_idx):
        """
        Load stimulus x and transformed h for a given contrast index.

        Parameters
        ----------
        contrast_idx : int
            Index of contrast level (0, 1, 2, ...)

        Returns
        -------
        x : np.ndarray
            Stimulus image patch (256,)
        h : np.ndarray
            GSM transformed input (50,)
        """
        x = np.loadtxt(self.data_path / f"x_{contrast_idx}")
        h = np.loadtxt(self.data_path / f"h_{contrast_idx}")
        return x, h

    def load_all_stimuli(self, indices=(0, 1, 2)):
        """
        Load all reference stimuli for specified contrast indices.

        Returns
        -------
        dict
            {contrast_idx: (x, h)}
        """
        return {i: self.load_stimulus(i) for i in indices}

    def load_transformation_parameters(self):
        """Load nonlinear transformation parameters for h_vec.

        These parameters are used to transform raw filter responses
        into SSN inputs via: h_transformed = α_h * max(h_vec + β_h, 0)^γ_h

        Returns
        -------
        dict
            Dictionary with keys 'alpha_h', 'beta_h', 'gamma_h'
            containing the optimized transformation parameters from
            Echeveste et al. (2020).

        Notes
        -----
        These parameters were optimized during the two-stage training
        procedure described in the paper. The raw h_vec files (h_0,
        h_1, h_2) contain filter responses that must be transformed
        using these parameters before being used as SSN inputs.

        References
        ----------
        parameters.md lines 32-34: Optimized values
        - α_h (input_scaling) = 1.96
        - β_h (input_baseline) = 0.10
        - γ_h (input_nl_pow) = 2.03
        """
        echeveste_data_path = self.data_path.parent / "echeveste2020"

        if not echeveste_data_path.exists():
            raise FileNotFoundError(
                f"Echeveste2020 data directory not found at "
                f"{echeveste_data_path}"
            )

        alpha_h = np.loadtxt(echeveste_data_path / "input_scaling")
        beta_h = np.loadtxt(echeveste_data_path / "input_baseline")
        gamma_h = np.loadtxt(echeveste_data_path / "input_nl_pow")

        return {
            'alpha_h': float(alpha_h),
            'beta_h': float(beta_h),
            'gamma_h': float(gamma_h)
        }

    def load_h_vec_transformed(self, contrast_idx):
        """Load precomputed h_true from files.

        IMPORTANT: The h_true files already have the nonlinear
        transformation applied and include both E and I neurons.

        Parameters
        ----------
        contrast_idx : int
            Index of contrast level (0=spontaneous, 1=low, 2=medium)

        Returns
        -------
        h_true : np.ndarray, shape (100,)
            Precomputed SSN input with transformation already applied
            Contains both E (first 50) and I (last 50) neurons

        Notes
        -----
        The h_true files are loaded from the original Echeveste code.
        They were generated by div_norm_data_GSM.py using:

        1. Generate GSM stimulus: x = z * (A @ y)
        2. Project with filters: x_proj = A.T @ x
        3. Scale: h_vec = (1/15) * x_proj
        4. Transform: h_true = α_h * (β_h + h_vec)^γ_h
        5. Duplicate: h_full = [h_true; h_true]

        The transformation was applied during data generation, so
        these files are ready to use directly in simulations without
        any additional processing.

        References
        ----------
        .. [1] div_norm_data_GSM.py lines 236-241, 352-353:
               get_true_h_from_x_proj() and its usage
        .. [2] full_net.py line 45:
               h[alpha] = np.loadtxt("h_true_"+str(alpha)+"_learn")
        """
        # Load h_true (already transformed, already duplicated)
        h_true = np.loadtxt(self.data_path / f"h_true_{contrast_idx}")

        # Validate that it has correct dimensions (100 = 50E + 50I)
        if h_true.shape[0] != 100:
            raise ValueError(
                f"h_true_{contrast_idx} has incorrect shape: "
                f"{h_true.shape}. Expected (100,) for 50E + 50I neurons."
            )

        # Validate that it's non-negative (transformation was applied)
        if np.any(h_true < 0):
            raise ValueError(
                f"h_true_{contrast_idx} contains negative values. "
                f"This suggests the file may not have the transformation "
                f"applied correctly."
            )

        # Validate duplication (E == I)
        h_exc = h_true[:50]
        h_inh = h_true[50:]
        if not np.allclose(h_exc, h_inh, rtol=1e-10):
            raise ValueError(
                f"h_true_{contrast_idx} excitatory and inhibitory inputs "
                f"do not match. Expected identical values."
            )

        return h_true

    # Validation
    def validate_data_integrity(self):
        """Validate that GSM data files exist and shapes are correct."""
        try:
            A = self.load_gabor_filters()
            assert A.shape == (256, 50), f"A shape {A.shape} != (256, 50)"

            C = self.load_prior_covariance()
            assert C.shape == (50, 50), f"C shape {C.shape} != (50, 50)"
            assert np.allclose(C, C.T, rtol=1e-10), "C must be symmetric"

            z_array = self.load_contrast_levels()
            assert z_array.ndim == 1, "z_array must be 1D"

            for i in [0, 1, 2]:
                x, h = self.load_stimulus(i)
                assert x.shape == (256,), f"x_{i} shape {x.shape} != (256,)"
                assert h.shape == (50,), f"h_{i} shape {h.shape} != (50,)"

            return True
        except Exception as e:
            print(f"GSM data validation failed: {e}")
            return False


# Convenience function
def load_gsm_data():
    """Return GSM data loader instance."""
    return GSMDataLoader()
